name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install-deps
      - name: Compile contracts
        run: make compile
      - name: Store contract artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts-artifacts
          path: build
      - name: Ganache Tests
        run: |
          SILENT=true make start-ganache
          make test
      - name: Forked Mainnet Tests
        run: |
          fuser -k 8545/tcp
          make start-forkedMainnet FORKED_TESTS_PROVIDER=${{ secrets.FORKED_TESTS_PROVIDER }}
          make test-forked

  coverage:
    needs: test
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download contracts artifacts
        uses: actions/download-artifact@v3
        with:
          name: contracts-artifacts
          path: build
      - name: Yarn install
        run: yarn install --frozen-lockfile
